name: credit
channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - jupyter
  - numpy
  - pandas
  - pyarrow
  - pyyaml
  - distributed

## dev and ML ops
  - pytest
  - ruff
  - pre_commit
  - myst-parser

## Earth sciences and visualization
  - xarray
  - netcdf4
  - zarr
  - xesmf
  - dask
  - dask-jobqueue
  - matplotlib
  - cartopy
  - ffmpeg

## ML
  - scikit-learn

  - pip:
    - mpi4py
    - einops
    - echo-opt
    - optuna==3.6.0
    - bridgescaler
    - torch 
    - torchvision 
    - segmentation-models-pytorch>=0.3.4
    - torch-harmonics
    - torch_geometric
    - haversine
    - torchsummary
    - sphinx-autoapi
    - properscoring
    - .

