name: credit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cpu
    - torchvision --index-url https://download.pytorch.org/whl/cpu
    - .
