# This is an example config file for testing the data loader and model training steps.  
# Yingkai Sha <ksha@ucar.edu>

save_loc: "/glade/work/$USER/repos/global/miles-credit/results/fuxi_new/"
seed: 1000

data:
    variables: ['U','V','T','Q']
    surface_variables: []
    forcing_variables: ['TSI'] #
    static_variables: ['Z_GDS4_SFC','LSM']
    diagnostic_variables: ['tp']
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT/EXTEND/TOTAL_*'
    save_loc_surface: '/glade/campaign/cisl/aiml/ksha/CREDIT/EXTEND/ERA5_regrid_tp_*'
    save_loc_forcing: '/glade/campaign/cisl/aiml/ksha/CREDIT/forcing_norm.nc'
    save_loc_static: '/glade/campaign/cisl/aiml/ksha/CREDIT/static_norm.nc'
    save_loc_diagnostic: '/glade/campaign/cisl/aiml/ksha/CREDIT/EXTEND/ERA5_regrid_tp_*'
    train_years: [1979, 2014]
    valid_years: [2014, 2018]
    mean_path: '/glade/campaign/cisl/aiml/ksha/CREDIT/EXTEND/All_2010_staged.mean.Lev.SLO.nc'
    std_path: '/glade/campaign/cisl/aiml/ksha/CREDIT/EXTEND/All_2010_staged.std.Lev.SLO.nc'
    scaler_type: 'std_new' # 'std'
    history_len: 2 
    forecast_len: 0 # larger than 0 for multi step
    valid_history_len: 2
    valid_forecast_len: 0 # 
    one_shot: True
    skip_periods: null
    
trainer:
    mode: none
    train_batch_size: 1
    valid_batch_size: 1
    batches_per_epoch: 5 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 5
    learning_rate: 1.0e-03
    weight_decay: 1.0e-05
    start_epoch: 0
    epochs: 20 # train_one_epoch: True
    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0
    thread_workers: 4
    valid_thread_workers: 0
    stopping_patience: 50
    teacher_forcing_ratio: 0.5 #0.9886539666794065
    stop_rollout: 0.9
    skip_validation: False
    load_weights: True
    load_optimizer: False
    use_scheduler: False
    #scheduler: {'scheduler_type': 'cosine-annealing', first_cycle_steps: 500, cycle_mult: 6.0, max_lr: 5.0e-04, min_lr: 5.0e-07, warmup_steps: 499, gamma: 0.7}
    # scheduler: {scheduler_type: plateau, mode: min, factor: 0.1, patience: 5, cooldown: 2, min_lr: 1e-6, epsilon: 1e-8, verbose: true, threshold: 1e-4}
    scheduler: {'scheduler_type': 'lambda'}
  
model:
    type: "fuxi"
    image_height: 640    # Image height (default: 640)
    patch_height: 4     # Patch height (default: 16)
    image_width: 1280    # Image width (default: 1280)
    patch_width: 4      # Patch width (default: 16)
    levels: 15           # Number of levels (default: 15)
    frames: 2            # Number of frames (default: 2)
    frame_patch_size: 2  # Frame patch size (default: 2)
    dim: 1024            # Dimension (default: 1536)
    num_groups: 32       # Number of groups (default: 32)
    channels: 4          # Channels (default: 4)
    surface_channels: 0  # Surface channels (default: 7)
    static_channels: 3   #
    diagnostic_channels: 1 #
    num_heads: 8         # Number of heads (default: 8)
    window_size: 7       # Window size (default: 7)
    depth: 8             # Depth of the swin transformer (default: 48)
    use_spectral_norm: True
    
loss: 
    training_loss: "mse"
    use_vgg: False
    use_power_loss: True # use either power or spectral loss
    use_spectral_loss: False
    spectral_wavenum_init: 20
    spectral_lambda_reg: 0.1 # power loss is order of 1e1 (usually between 1-10)
    use_latitude_weights: True
    latitude_weights: "/glade/u/home/wchapman/MLWPS/DataLoader/LSM_static_variables_ERA5_zhght.nc"
    use_variable_weights: False
    variable_weights:
        U: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
        V: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
        T: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
        Q: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
        SP: 0.1
        t2m: 1.0
        V500: 0.1
        U500: 0.1
        T500: 0.1
        Z500: 0.1
        Q500: 0.1

predict:
    forecasts: [
        #["1989-12-31 00:00:00", "1990-01-02 00:00:00"],
        ["2018-06-01 00:00:00", "2018-06-01 02:00:00"]
    ]
    use_laplace_filter: True
    metadata: '/glade/u/home/ksha/miles-credit/credit/metadata/era5.yaml'
    save_forecast: '/glade/derecho/scratch/ksha/CREDIT/fuxi/'
    save_vars: ['SP','t2m','V500','U500','T500','Z500','Q500']
    save_format: "nc"

visualization:
    sigma_level_visualize:
        variable_keys: ['U','V','T','Q']  # variable keys as defined in **[data][variables][...]**
        visualize_levels: [5, 10,]     # sigma levels (by their indices) to visualize 
        variable_names: ['U wind [m/s]', # the name of each variable
                         'V wind [m/s]', # must be consistent with **variable_indices**
                         'Air temperature [$^\circ$K]',
                         'Specific humidity [kg/kg]']
        variable_factors: [1, 1, 1, 1]
        variable_range: [auto, auto, auto, auto] # use auto or provide a list of [min_var, max_var]; it applies to all levels
        colormaps: ['Spectral_r', 'Spectral_r', 'viridis_plasma', 'YlGn']
        file_name_prefix: 'global_sigma'
    diagnostic_variable_visualize:
        variable_keys: ['V500', 'U500','T500','Z500','Q500']
        visualize_levels: ['none', 'none', 'none', 'none', 'none'] # none for single level variables
        variable_names: ['500 hPa V Wind [m/s]', 
                         '500 hPa U Wind [m/s]',
                         '500 hPa Air temperature [$^\circ$K]',
                         '500 hPa Geopotential Height [km]',
                         '500 hPa Specific humidity [kg/kg]']
        variable_factors: [1, 1, 1, 0.001, 1]
        variable_range: [auto, auto, [220, 300], [50, 60], auto]
        colormaps: ['Spectral_r', 'Spectral_r', 'viridis_plasma', 'Spectral_r', 'YlGn']
        file_name_prefix: 'global_diagnostics'
    surface_visualize:
        variable_keys: ['SP','t2m']
        visualize_levels: ['none', 'none']
        variable_names: ['Surface Pressure [hPa]', 
                         '2-m Air Temperature [$^\circ$K]']
        variable_factors: [0.01, 1]
        variable_range: [[650, 1100], [200, 350]]
        colormaps: ['Spectral', 'viridis_plasma',]
        file_name_prefix: 'global_surface'
    map_projection: 'EckertIII' # PlateCarree, LambertCylindrical, Miller, EckertIII, Mollweide, Robinson
    save_options: {'dpi':250, 
                   'orientation':'portrait', 
                   'bbox_inches':'tight', 
                   'pad_inches':0.1, 
                   'transparent':False,
                   'format':'png'}
    video_format: 'mp4' # gif, mp4, none


pbs: #derecho
    conda: "/glade/work/ksha/miniconda3/envs/credit"
    project: "NAML0001"
    job_name: "fuxi_norm"
    walltime: "12:00:00"
    nodes: 8
    ncpus: 64
    ngpus: 4
    mem: '480GB'
    queue: 'main'

# pbs: # casper
#     conda: "/glade/work/ksha/miniconda3/envs/credit"
#     project: "NAML0001"
#     job_name: 'FuXi_Lite'
#     nodes: 1
#     ncpus: 16
#     ngpus: 1
#     mem: '128GB'
#     walltime: '24:00:00'
#     gpu_type: 'a100'
#     cpu_type: 'milan'
#     queue: 'casper'
